name: Test
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/**"
jobs:
  test:
    defaults:
      run:
        working-directory: __tests__
    env:
      NODE_VERSION: 20.15.0

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Execute Unit Tests
        run: |
          npm ci
          npm test
